[package]
name = "db-sqlite"
version = "1.0.0"
edition = "2021"

# Do not use workspace deps as they this package isn't part of the workspace.
[dependencies]
actix-web = "4"
env_logger = "0.11"
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
log = "0.4"
r2d2 = "0.8"
r2d2_sqlite = "0.24"
rusqlite = "0.31"
serde = { version = "1", features = ["derive"] }
